### ISSUE TITLE
Consider adding Maybe.prototype.filter

### ISSUE THREAD

**Issue by uniphil** [uniphil/results#87]
We have a number of pieces of code at OpenRide where we want to conditionally operate on a `Maybe` value like

``` js
someMaybeThing
  .andThen(x => (expr) ? x : Maybe.None())
  .andThen(...);
```

This feels a lot like a `blahArray.filter(x => (expr)).map(...)`, but it's more awkward to write. It would be nice to be able to do the same:

``` js
someMaybeThing
  .filter(x => (expr))
  .andThen(...);
```
1. I don't know if `filter` is the right name -- makes it look like an Array.
2. A helper function could also do this:

``` js
const filterMaybe = test => value =>
  test(value) ? Maybe.Some(value) : Maybe.None();


someMaybeThing(
  .andThen(filterMaybe(x => (expr)))
  .andThen(...);
```

@mystor I'm interested in your thoughts on this. I haven't seen a method like `.filter` on other `Maybe`s, like Rust's or Elm's.

**Comment by mystor** [comment]
That makes sense to me as an operation. I would think that filter is a fine name for the method. I figure that the operation isn't available on rust's Option<T> type just because it's not used super frequently.

**Comment by uniphil** [comment]
Cool. I think I'll add it then.
